name = "LabReports"
uuid = "bbdd1d1c-360a-4eda-95a3-67690d35087a"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
